name: Uget-Release

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write
    id-token: write

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.24.2

            - name: Build for amd64
              env:
                  GOOS: windows
                  GOARCH: amd64
              run: |
                  go build -ldflags="-s -w" -trimpath -o uget-windows-amd64-${{ github.ref_name }}.exe

            - name: Build for arm64
              env:
                  GOOS: windows
                  GOARCH: arm64
              run: |
                  go build -ldflags="-s -w" -trimpath -o uget-windows-arm64-${{ github.ref_name }}.exe

            - name: List files for debugging
              run: ls -R

            - name: Create Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  files: |
                      uget-windows-amd64-${{ github.ref_name }}.exe
                      uget-windows-arm64-${{ github.ref_name }}.exe
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
